### ISSUE TITLE
Install Cloud9 SDK on port 8089?

### ISSUE THREAD

**Issue by jankeromnes** [rcatolino/kdesrcbuild-docker#2]
We're trying to switch Janitor away from the third-party service https://c9.io by installing the Cloud9 IDE locally, using their SDK.

It would be cool if, for compatibility reasons, the KDE image installed Cloud9 SDK, and had it running on port 8089, e.g. like so:

- [Installing Cloud9 SDK](https://github.com/JanitorTechnology/dockerfiles/blob/7a8d767062eb2c1a751e3650953feba901f8fa6d/ubuntu-dev/ubuntu-dev.dockerfile#L177-L187)
- [Exposing port 8089](https://github.com/JanitorTechnology/dockerfiles/blob/7a8d767062eb2c1a751e3650953feba901f8fa6d/ubuntu-dev/ubuntu-dev.dockerfile#L193)
- [Running Cloud9 SDK via supervisor](https://github.com/JanitorTechnology/dockerfiles/blob/7a8d767062eb2c1a751e3650953feba901f8fa6d/ubuntu-dev/supervisord.conf#L8-L10)

Notes:
- We also install a few additional plugins, using a custom workspace type, but the most important thing is to run a Cloud9 SDK on port 8089 (so you don't have to worry about the plugins and the workspace type if that seems like too much work)
- You should probably set `workspace` in the supervisor configuration directly to `/home/user/work` or `/home/user/kdesrc-build/` (whichever makes the most sense as the root folder in Cloud9).

**Comment by rcatolino** [comment]
The dockerfile is now based on janx/ubuntu-dev, which takes care of compatibility with janitor.

**Comment by jankeromnes** [comment]
Wooo! This is exciting news, thanks a lot @rcatolino!
