### ISSUE TITLE
Please set up an automated build on Docker Hub

### ISSUE THREAD

**Issue by jankeromnes** [rcatolino/kdesrcbuild-docker#3]
Currently, this Dockerfile is being built as [janitortechnology/kde](https://hub.docker.com/r/janitortechnology/kde/), but this is not ideal as it is based on the (usually outdated) Git submodule in https://github.com/JanitorTechnology/dockerfiles.

A better, more direct solution would be if you could log into https://hub.docker.com, then click on `Create Automated Build`, and configure it for this GitHub repository / Dockerfile. This will automatically build and deploy a Docker image, whenever new commits are pushed to this repository.

(You can then also manually link the Automated Build with the `janx/ubuntu-dev` image, so that the Dockerfile also gets rebuilt when a new `ubuntu-dev` is available.)

Note that you already have a KDE image on Docker Hub, [rcay/kdecore](https://hub.docker.com/r/rcay/kdecore/), but it was pushed manually, which is different from an Automated Build.

**Comment by rcatolino** [comment]
Done. For some reason I had to create a new docker hub project, it's now [rcay/kdesrcbuild-docker](https://hub.docker.com/r/rcay/kdesrcbuild-docker). I'll update janitor when it's done building.

**Comment by jankeromnes** [comment]
Amazing! Thanks a lot! As soon as it has a successful build, I'll switch Janitor's KDE image over to it.

**Comment by jankeromnes** [comment]
Re-opening, as it seems that the build times out (if my interpretation of their "Build canceled." error message is correct.)

https://hub.docker.com/r/rcay/kdesrcbuild-docker/builds/bbkmx3fmuyfrbbealuathk6/ shows a good-looking build, which gets canceled in its last step:

```
Step 37/37 : RUN ./kdesrc-build --include-dependencies frameworks || true

[...]

Building attica from frameworks (24/81)

	No source update, but the build directory doesn't exist
	Updating attica (to branch master)
	Source update complete for attica: no files affected

	Preparing build system for attica.

	Running cmake...

	Compiling...

Build canceled.
```

Apparently, the build was canceled just after the 2 hours mark, which leads me to believe this is a time out.

Is there way to make the build faster than 2 hours? If not, we can automate it via Circle CI (which has more powerful hardware and longer timeouts).

EDIT: @rcatolino FYI I'm not authorized to re-open this issue. Please re-open or open a new issue, whatever you prefer. 😄

**Comment by jankeromnes** [comment]
This was fixed by https://github.com/JanitorTechnology/dockerfiles/commit/c0133c643b5c908557e82bd9b35759943a590f32, and the (Circle CI) automated build is now live at https://hub.docker.com/r/janitortechnology/kde/

Thanks! 😄 👍 🎉
